#source common.sh
#
#print_head "Copy Mongo Repo File"
#cp ${script_location}/files/mongodb.repo  /etc/yum.repos.d/mongodb.repo &>>${LOG}
#status_check
#
#print_head "v"
#dnf install mongodb-org -y &>>${LOG}
#status_check
#
#print_head "Update MongoDB Listen address"
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf &>>${LOG}
#status_check
#
#print_head "Enable Mongod Service"
#systemctl enable mongod &>>${LOG}
#status_check
#
#print_head "Restart Mongod Service"
#systemctl restart mongod &>>${LOG}
#status_check



- name: Copy Mongo Repo File
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb server
  ansible.builtin.yum:
    name: mongodb-org
    state: present

- name: Update MongoDB Listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regex: 127.0.0.1
    replace: 0.0.0.0

- name: Start Mongod
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes