- name: Create AWS SSM parameter store
  hosts: localhost
  connection: local
  tasks:
    - name: Create AWS SSM parameters
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: us-east-1
      loop:
        - {name: "dev.cart.REDIS_HOST", value: "redis-dev.tushardevops.online"}
        - {name: "dev.cart.CATALOGUE_HOST", value: "catalogue-dev.tushardevops.online"}
        - {name: "dev.catalogue.MONGO", value: "true"}
        - {name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.tushardevops.online:27017/catalogue"}
        - {name: "dev.frontend.CATALOGUE_URL", value: "http://catalogue-dev.tushardevops.online:8080/"}
        - {name: "dev.frontend.USER_URL", value: "http://user-dev.tushardevops.online:8080/"}
        - {name: "dev.frontend.CART_URL", value: "http://cart-dev.tushardevops.online:8080/"}
        - {name: "dev.frontend.SHIPPING_URL", value: "http://shipping-dev.tushardevops.online:8080/"}
        - {name: "dev.frontend.PAYMENT_URL", value: "http://payment-dev.tushardevops.online:8080/"}
        - {name: "dev.payment.CART_HOST", value: "cart-dev.tushardevops.online"}
        - {name: "dev.payment.USER_HOST", value: "user-dev.tushardevops.online"}
        - {name: "dev.payment.CART_PORT", value: "8080"}
        - {name: "dev.payment.USER_PORT", value: "8080"}
        - {name: "dev.payment.AMQP_HOST", value: "rabbitmq-dev.tushardevops.online"}
        - {name: "dev.payment.AMQP_USER", value: "roboshop"}
        - { name: "dev.shipping.CART_ENDPOINT", value: "cart-dev.tushardevops.online:8080" }
        - { name: "dev.shipping.DB_HOST", value: "mysql-dev.tushardevops.online" }
        - { name: "dev.user.REDIS_HOST", value: "redis-dev.tushardevops.online" }
        - { name: "dev.user.MONGO_URL", value: "mongodb://mongodb-dev.tushardevops.online:27017/users" }

        ###PASSWORDS SHOULD NEVER BE KEEP IN THESE REPOS. THOSE SHOULD BE CREATED MANUALLY, BUT FOR LAB PURPOSE IM CREATING HERE
    - name: Create AWS SSM Secrets
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: us-east-1
        string_type: "SecureString"
      loop:
        - {name: "dev.payment.AMQP_PASS", value: "roboshop123"}
        - { name: "dev.mysql.DB_ADMIN_USER", value: "root" }
        - { name: "dev.mysql.DB_ADMIN_PASS", value: "RoboShop@1" }
        - {name: "dev.rabbitmq.AMQP_PASS", value: "roboshop123" }
        - { name: "dev.docdb.DB_ADMIN_USER", value: "admin1" }
        - { name: "dev.docdb.DB_ADMIN_PASS", value: "RoboShop123" }
