- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: present

- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: Remove old App Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download {{component}} App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes