- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: present

- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: Remove old App Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download {{component}} App content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Download {{component}} App content
  ansible.builtin.unarchive:
    src: http://{{nexus_user}}:{{nexus_pass}}@172.31.37.151:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes
  vars:
    nexus_user: "{{ lookup('aws_ssm', 'nexus.user', region='us-east-1' ) }}"
    nexus_pass: "{{ lookup('aws_ssm', 'nexus.pass', region='us-east-1' ) }}"