- name: Copy Mongo Repo File
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb server
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: present

- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.tushardevops.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes