- name: Install MySQL Client
  ansible.builtin.yum:
    name:
      - python3-PyMySQL
      - mysql
    state: present

- name: Load MySQL Schema
  community.mysql.mysql_db:
    state: import
    name: all
    encoding: latin1
    target: /app/schema/{{component}}.sql
    login_host: mysql-dev.tushardevops.online
    login_user: root
    login_password: "{{root_mysql_password}}"
  vars:
    root_mysql_password: "{{ lookup('aws_ssm', '{{env}}.mysql.DB_ADMIN_PASS', region='us-east-1' ) }}"
