- name: Test
  ansible.builtin.debug:
    msg: Hello from {{component}}

- name : Configure NodeJS Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: present

- name: App PreReq
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Installing NodeJS Dependencies
  community.general.npm:
    path: /app
    state: latest

- name: App PreReq
  ansible.builtin.include_tasks: "systemd.yml"

- name: load schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load