
- name: Setup Redis Repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true

- name: Install Redis server
  ansible.builtin.yum:
    name: redis
    state: present

- name: Update Redis Listen address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Start Redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes